import React from "react";

export const Chart: React.FC = ({ children }) => {
  return (
    <svg width="730" height="250" viewBox="0 0 730 250" version="1.1">
      <defs>
        <clipPath id="recharts30-clip">
          <rect x="70" y="20" height="166" width="640"></rect>
        </clipPath>
      </defs>
      <g>
        <g>
          <line
            stroke-dasharray="3 3"
            stroke="#ccc"
            fill="none"
            x="70"
            y="20"
            width="640"
            height="166"
            offset="[object Object]"
            x1="70"
            y1="186"
            x2="710"
            y2="186"
          ></line>
          <line
            stroke-dasharray="3 3"
            stroke="#ccc"
            fill="none"
            x="70"
            y="20"
            width="640"
            height="166"
            offset="[object Object]"
            x1="70"
            y1="144.5"
            x2="710"
            y2="144.5"
          ></line>
          <line
            stroke-dasharray="3 3"
            stroke="#ccc"
            fill="none"
            x="70"
            y="20"
            width="640"
            height="166"
            offset="[object Object]"
            x1="70"
            y1="103"
            x2="710"
            y2="103"
          ></line>
          <line
            stroke-dasharray="3 3"
            stroke="#ccc"
            fill="none"
            x="70"
            y="20"
            width="640"
            height="166"
            offset="[object Object]"
            x1="70"
            y1="61.5"
            x2="710"
            y2="61.5"
          ></line>
          <line
            stroke-dasharray="3 3"
            stroke="#ccc"
            fill="none"
            x="70"
            y="20"
            width="640"
            height="166"
            offset="[object Object]"
            x1="70"
            y1="20"
            x2="710"
            y2="20"
          ></line>
        </g>
        <g>
          <line
            stroke-dasharray="3 3"
            stroke="#ccc"
            fill="none"
            x="70"
            y="20"
            width="640"
            height="166"
            offset="[object Object]"
            x1="111.60000000000001"
            y1="20"
            x2="111.60000000000001"
            y2="186"
          ></line>
          <line
            stroke-dasharray="3 3"
            stroke="#ccc"
            fill="none"
            x="70"
            y="20"
            width="640"
            height="166"
            offset="[object Object]"
            x1="165.35999999999999"
            y1="20"
            x2="165.35999999999999"
            y2="186"
          ></line>
          <line
            stroke-dasharray="3 3"
            stroke="#ccc"
            fill="none"
            x="70"
            y="20"
            width="640"
            height="166"
            offset="[object Object]"
            x1="219.11999999999998"
            y1="20"
            x2="219.11999999999998"
            y2="186"
          ></line>
          <line
            stroke-dasharray="3 3"
            stroke="#ccc"
            fill="none"
            x="70"
            y="20"
            width="640"
            height="166"
            offset="[object Object]"
            x1="272.88"
            y1="20"
            x2="272.88"
            y2="186"
          ></line>
          <line
            stroke-dasharray="3 3"
            stroke="#ccc"
            fill="none"
            x="70"
            y="20"
            width="640"
            height="166"
            offset="[object Object]"
            x1="329.2"
            y1="20"
            x2="329.2"
            y2="186"
          ></line>
          <line
            stroke-dasharray="3 3"
            stroke="#ccc"
            fill="none"
            x="70"
            y="20"
            width="640"
            height="166"
            offset="[object Object]"
            x1="385.52"
            y1="20"
            x2="385.52"
            y2="186"
          ></line>
          <line
            stroke-dasharray="3 3"
            stroke="#ccc"
            fill="none"
            x="70"
            y="20"
            width="640"
            height="166"
            offset="[object Object]"
            x1="441.84"
            y1="20"
            x2="441.84"
            y2="186"
          ></line>
          <line
            stroke-dasharray="3 3"
            stroke="#ccc"
            fill="none"
            x="70"
            y="20"
            width="640"
            height="166"
            offset="[object Object]"
            x1="495.6"
            y1="20"
            x2="495.6"
            y2="186"
          ></line>
          <line
            stroke-dasharray="3 3"
            stroke="#ccc"
            fill="none"
            x="70"
            y="20"
            width="640"
            height="166"
            offset="[object Object]"
            x1="549.36"
            y1="20"
            x2="549.36"
            y2="186"
          ></line>
          <line
            stroke-dasharray="3 3"
            stroke="#ccc"
            fill="none"
            x="70"
            y="20"
            width="640"
            height="166"
            offset="[object Object]"
            x1="592.88"
            y1="20"
            x2="592.88"
            y2="186"
          ></line>
          <line
            stroke-dasharray="3 3"
            stroke="#ccc"
            fill="none"
            x="70"
            y="20"
            width="640"
            height="166"
            offset="[object Object]"
            x1="645.36"
            y1="20"
            x2="645.36"
            y2="186"
          ></line>
          <line
            stroke-dasharray="3 3"
            stroke="#ccc"
            fill="none"
            x="70"
            y="20"
            width="640"
            height="166"
            offset="[object Object]"
            x1="709.36"
            y1="20"
            x2="709.36"
            y2="186"
          ></line>
          <line
            stroke-dasharray="3 3"
            stroke="#ccc"
            fill="none"
            x="70"
            y="20"
            width="640"
            height="166"
            offset="[object Object]"
            x1="70"
            y1="20"
            x2="70"
            y2="186"
          ></line>
          <line
            stroke-dasharray="3 3"
            stroke="#ccc"
            fill="none"
            x="70"
            y="20"
            width="640"
            height="166"
            offset="[object Object]"
            x1="710"
            y1="20"
            x2="710"
            y2="186"
          ></line>
        </g>
      </g>
      <g>
        <line
          name="stature"
          orientation="bottom"
          width="640"
          height="30"
          type="category"
          x="70"
          y="186"
          stroke="#666"
          fill="none"
          x1="70"
          y1="186"
          x2="710"
          y2="186"
        ></line>
        <g>
          <g>
            <line
              name="stature"
              orientation="bottom"
              width="640"
              height="30"
              type="category"
              x="70"
              y="186"
              stroke="#666"
              fill="none"
              x1="111.60000000000001"
              y1="192"
              x2="111.60000000000001"
              y2="186"
            ></line>
            <text
              name="stature"
              orientation="bottom"
              width="640"
              height="30"
              type="category"
              x="111.60000000000001"
              y="194"
              stroke="none"
              fill="#666"
              text-anchor="middle"
            >
              <tspan x="111.60000000000001" dy="0.71em">
                171cm
              </tspan>
            </text>
          </g>
          <g>
            <line
              name="stature"
              orientation="bottom"
              width="640"
              height="30"
              type="category"
              x="70"
              y="186"
              stroke="#666"
              fill="none"
              x1="165.35999999999999"
              y1="192"
              x2="165.35999999999999"
              y2="186"
            ></line>
            <text
              name="stature"
              orientation="bottom"
              width="640"
              height="30"
              type="category"
              x="165.35999999999999"
              y="194"
              stroke="none"
              fill="#666"
              text-anchor="middle"
            >
              <tspan x="165.35999999999999" dy="0.71em">
                149cm
              </tspan>
            </text>
          </g>
          <g>
            <line
              name="stature"
              orientation="bottom"
              width="640"
              height="30"
              type="category"
              x="70"
              y="186"
              stroke="#666"
              fill="none"
              x1="219.11999999999998"
              y1="192"
              x2="219.11999999999998"
              y2="186"
            ></line>
            <text
              name="stature"
              orientation="bottom"
              width="640"
              height="30"
              type="category"
              x="219.11999999999998"
              y="194"
              stroke="none"
              fill="#666"
              text-anchor="middle"
            >
              <tspan x="219.11999999999998" dy="0.71em">
                65cm
              </tspan>
            </text>
          </g>
          <g>
            <line
              name="stature"
              orientation="bottom"
              width="640"
              height="30"
              type="category"
              x="70"
              y="186"
              stroke="#666"
              fill="none"
              x1="272.88"
              y1="192"
              x2="272.88"
              y2="186"
            ></line>
            <text
              name="stature"
              orientation="bottom"
              width="640"
              height="30"
              type="category"
              x="272.88"
              y="194"
              stroke="none"
              fill="#666"
              text-anchor="middle"
            >
              <tspan x="272.88" dy="0.71em">
                309cm
              </tspan>
            </text>
          </g>
          <g>
            <line
              name="stature"
              orientation="bottom"
              width="640"
              height="30"
              type="category"
              x="70"
              y="186"
              stroke="#666"
              fill="none"
              x1="329.2"
              y1="192"
              x2="329.2"
              y2="186"
            ></line>
            <text
              name="stature"
              orientation="bottom"
              width="640"
              height="30"
              type="category"
              x="329.2"
              y="194"
              stroke="none"
              fill="#666"
              text-anchor="middle"
            >
              <tspan x="329.2" dy="0.71em">
                315cm
              </tspan>
            </text>
          </g>
          <g>
            <line
              name="stature"
              orientation="bottom"
              width="640"
              height="30"
              type="category"
              x="70"
              y="186"
              stroke="#666"
              fill="none"
              x1="385.52"
              y1="192"
              x2="385.52"
              y2="186"
            ></line>
            <text
              name="stature"
              orientation="bottom"
              width="640"
              height="30"
              type="category"
              x="385.52"
              y="194"
              stroke="none"
              fill="#666"
              text-anchor="middle"
            >
              <tspan x="385.52" dy="0.71em">
                244cm
              </tspan>
            </text>
          </g>
          <g>
            <line
              name="stature"
              orientation="bottom"
              width="640"
              height="30"
              type="category"
              x="70"
              y="186"
              stroke="#666"
              fill="none"
              x1="441.84"
              y1="192"
              x2="441.84"
              y2="186"
            ></line>
            <text
              name="stature"
              orientation="bottom"
              width="640"
              height="30"
              type="category"
              x="441.84"
              y="194"
              stroke="none"
              fill="#666"
              text-anchor="middle"
            >
              <tspan x="441.84" dy="0.71em">
                517cm
              </tspan>
            </text>
          </g>
          <g>
            <line
              name="stature"
              orientation="bottom"
              width="640"
              height="30"
              type="category"
              x="70"
              y="186"
              stroke="#666"
              fill="none"
              x1="495.6"
              y1="192"
              x2="495.6"
              y2="186"
            ></line>
            <text
              name="stature"
              orientation="bottom"
              width="640"
              height="30"
              type="category"
              x="495.6"
              y="194"
              stroke="none"
              fill="#666"
              text-anchor="middle"
            >
              <tspan x="495.6" dy="0.71em">
                119cm
              </tspan>
            </text>
          </g>
          <g>
            <line
              name="stature"
              orientation="bottom"
              width="640"
              height="30"
              type="category"
              x="70"
              y="186"
              stroke="#666"
              fill="none"
              x1="549.36"
              y1="192"
              x2="549.36"
              y2="186"
            ></line>
            <text
              name="stature"
              orientation="bottom"
              width="640"
              height="30"
              type="category"
              x="549.36"
              y="194"
              stroke="none"
              fill="#666"
              text-anchor="middle"
            >
              <tspan x="549.36" dy="0.71em">
                84cm
              </tspan>
            </text>
          </g>
          <g>
            <line
              name="stature"
              orientation="bottom"
              width="640"
              height="30"
              type="category"
              x="70"
              y="186"
              stroke="#666"
              fill="none"
              x1="592.88"
              y1="192"
              x2="592.88"
              y2="186"
            ></line>
            <text
              name="stature"
              orientation="bottom"
              width="640"
              height="30"
              type="category"
              x="592.88"
              y="194"
              stroke="none"
              fill="#666"
              text-anchor="middle"
            >
              <tspan x="592.88" dy="0.71em">
                7cm
              </tspan>
            </text>
          </g>
          <g>
            <line
              name="stature"
              orientation="bottom"
              width="640"
              height="30"
              type="category"
              x="70"
              y="186"
              stroke="#666"
              fill="none"
              x1="645.36"
              y1="192"
              x2="645.36"
              y2="186"
            ></line>
            <text
              name="stature"
              orientation="bottom"
              width="640"
              height="30"
              type="category"
              x="645.36"
              y="194"
              stroke="none"
              fill="#666"
              text-anchor="middle"
            >
              <tspan x="645.36" dy="0.71em">
                15cm
              </tspan>
            </text>
          </g>
          <g>
            <line
              name="stature"
              orientation="bottom"
              width="640"
              height="30"
              type="category"
              x="70"
              y="186"
              stroke="#666"
              fill="none"
              x1="709.36"
              y1="192"
              x2="709.36"
              y2="186"
            ></line>
            <text
              name="stature"
              orientation="bottom"
              width="640"
              height="30"
              type="category"
              x="703.2109375"
              y="194"
              stroke="none"
              fill="#666"
              text-anchor="middle"
            >
              <tspan x="703.2109375" dy="0.71em">
                684cm
              </tspan>
            </text>
          </g>
        </g>
      </g>
      <g>
        <line
          name="weight"
          orientation="left"
          width="60"
          height="166"
          type="number"
          x="10"
          y="20"
          stroke="#666"
          fill="none"
          x1="70"
          y1="20"
          x2="70"
          y2="186"
        ></line>
        <g>
          <g>
            <line
              name="weight"
              orientation="left"
              width="60"
              height="166"
              type="number"
              x="10"
              y="20"
              stroke="#666"
              fill="none"
              x1="64"
              y1="186"
              x2="70"
              y2="186"
            ></line>
            <text
              name="weight"
              orientation="left"
              width="60"
              height="166"
              type="number"
              x="62"
              y="186"
              stroke="none"
              fill="#666"
              text-anchor="end"
            >
              <tspan x="62" dy="0.355em">
                0kg
              </tspan>
            </text>
          </g>
          <g>
            <line
              name="weight"
              orientation="left"
              width="60"
              height="166"
              type="number"
              x="10"
              y="20"
              stroke="#666"
              fill="none"
              x1="64"
              y1="144.5"
              x2="70"
              y2="144.5"
            ></line>
            <text
              name="weight"
              orientation="left"
              width="60"
              height="166"
              type="number"
              x="62"
              y="144.5"
              stroke="none"
              fill="#666"
              text-anchor="end"
            >
              <tspan x="62" dy="0.355em">
                250kg
              </tspan>
            </text>
          </g>
          <g>
            <line
              name="weight"
              orientation="left"
              width="60"
              height="166"
              type="number"
              x="10"
              y="20"
              stroke="#666"
              fill="none"
              x1="64"
              y1="103"
              x2="70"
              y2="103"
            ></line>
            <text
              name="weight"
              orientation="left"
              width="60"
              height="166"
              type="number"
              x="62"
              y="103"
              stroke="none"
              fill="#666"
              text-anchor="end"
            >
              <tspan x="62" dy="0.355em">
                500kg
              </tspan>
            </text>
          </g>
          <g>
            <line
              name="weight"
              orientation="left"
              width="60"
              height="166"
              type="number"
              x="10"
              y="20"
              stroke="#666"
              fill="none"
              x1="64"
              y1="61.5"
              x2="70"
              y2="61.5"
            ></line>
            <text
              name="weight"
              orientation="left"
              width="60"
              height="166"
              type="number"
              x="62"
              y="61.5"
              stroke="none"
              fill="#666"
              text-anchor="end"
            >
              <tspan x="62" dy="0.355em">
                750kg
              </tspan>
            </text>
          </g>
          <g>
            <line
              name="weight"
              orientation="left"
              width="60"
              height="166"
              type="number"
              x="10"
              y="20"
              stroke="#666"
              fill="none"
              x1="64"
              y1="20"
              x2="70"
              y2="20"
            ></line>
            <text
              name="weight"
              orientation="left"
              width="60"
              height="166"
              type="number"
              x="62"
              y="20"
              stroke="none"
              fill="#666"
              text-anchor="end"
            >
              <tspan x="62" dy="0.355em">
                1000kg
              </tspan>
            </text>
          </g>
        </g>
      </g>
      {children}
    </svg>
  );
};
